policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: true
      spellcheck:
        locale: UK
      maximumOfOneCommit: false
      conventional:
        types:
          - "fix"
          - "feat"
          - "chore"
          - "perf"
          - "refactor"
          - "style"
        descriptionLength: 72
