policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: true
      spellcheck:
        locale: UK
      maximumOfOneCommit: false
      conventional:
        types:
          - "type"
        scopes:
          - "scope"
        descriptionLength: 72